services:
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boujou
    volumes:
      - data:/var/lib/postgresql/data

  test:
    build: .
    image: boujou
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/boujou
      - GEOCODE_API=66a0a75ad545b465733868xfv7ddcd9
      - ENV=db
    command: "npm run vitest"

volumes:
  data:
