name: Test Boujou
run-name: ${{ github.actor }} initializing GitHub Actions
on:
  push:
    branches:
      - "97-test-unitaire-e2e"
  # push:
  #   branches:
  #     - main
  #     - develop
  # pull_request:
  #   branches:
  #     - main
  #     - develop
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{ toJSON(secrets) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # - name: Cache Node.js modules and Cypress
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cache/Cypress
      #       node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint
  deploy-development:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: development
      url: http://MON_IP:3001
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/geoffroybel/boujou2:latest
