name: Test Boujou
run-name: ${{ github.actor }} initializing GitHub Actions
on:
  push:
    branches:
      - feat#1-cicd
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{ toJSON(github) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
